// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8meoktal18RK5FotUqEeKUmCzGnwU9E',
    appId: '1:275985949336:web:c0558fca128f40f5c7e6ed',
    messagingSenderId: '275985949336',
    projectId: 'thamara-fc885',
    authDomain: 'thamara-fc885.firebaseapp.com',
    storageBucket: 'thamara-fc885.firebasestorage.app',
    measurementId: 'G-E54M76RPCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZd-9h_Yy1klAIpeS_cRaOhYc_rfJe9w',
    appId: '1:275985949336:android:f5360d5d475e29f9c7e6ed',
    messagingSenderId: '275985949336',
    projectId: 'thamara-fc885',
    storageBucket: 'thamara-fc885.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNjvstUzIjhuW9HZskiHNwtf9V8ZH4qow',
    appId: '1:275985949336:ios:572ad738b4138c99c7e6ed',
    messagingSenderId: '275985949336',
    projectId: 'thamara-fc885',
    storageBucket: 'thamara-fc885.firebasestorage.app',
    iosBundleId: 'com.example.thamara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNjvstUzIjhuW9HZskiHNwtf9V8ZH4qow',
    appId: '1:275985949336:ios:572ad738b4138c99c7e6ed',
    messagingSenderId: '275985949336',
    projectId: 'thamara-fc885',
    storageBucket: 'thamara-fc885.firebasestorage.app',
    iosBundleId: 'com.example.thamara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx8meoktal18RK5FotUqEeKUmCzGnwU9E',
    appId: '1:275985949336:web:88a7587da07fe048c7e6ed',
    messagingSenderId: '275985949336',
    projectId: 'thamara-fc885',
    authDomain: 'thamara-fc885.firebaseapp.com',
    storageBucket: 'thamara-fc885.firebasestorage.app',
    measurementId: 'G-3LCHWH8DMW',
  );
}
